<?php
/**
 * Privacy-safe attribution for the jus-tice.com product-to-professional handoff.
 *
 * The journey ID is a random browser-session correlation key. It is not an
 * authentication credential, a Matter ID, or permission to read product data.
 * No title, facts, evidence, transcript, score, person or contact detail is
 * accepted by this contract.
 *
 * @package JusticeTheme
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Return the canonical owner pages for the reconciled GSC architecture.
 *
 * @return array<string,string>
 */
function justice_theme_product_handoff_cluster_owners(): array {
	return array(
		'family-law'                => '/divorce-lawyer/',
		'criminal-law'              => '/criminal-defense-attorney/',
		'real-estate'               => '/articles/real-estate-attorney/',
		'immigration'               => '/immigration-lawyer/',
		'international-real-estate' => '/buying-property-abroad-guide/',
		'traffic-law'               => '/articles/traffic-lawyer/',
		'inheritance'               => '/inheritance-lawyer/',
		'employment'                => '/labor-lawyer/',
		'medical-malpractice'       => '/medical-malpractice-lawyer/',
		'personal-injury'           => '/personal-injury-law/',
		'tax'                       => '/real-estate-tax-advisor/',
	);
}

/**
 * Return the launch-safe product scenario owned by each GSC cluster.
 *
 * @return array<string,string>
 */
function justice_theme_product_handoff_cluster_scenarios(): array {
	return array(
		'family-law'                => 'mediation-preparation',
		'criminal-law'              => 'investigation-rehearsal',
		'real-estate'               => 'transaction-dispute-rehearsal',
		'immigration'               => 'immigration-interview-preparation',
		'international-real-estate' => 'cross-border-transaction-review',
		'traffic-law'               => 'traffic-hearing-rehearsal',
		'inheritance'               => 'probate-dispute-preparation',
		'employment'                => 'employment-dispute-rehearsal',
		'medical-malpractice'       => 'medical-expert-preparation',
		'personal-injury'           => 'damages-testimony-preparation',
		'tax'                       => 'tax-review-preparation',
	);
}

/**
 * Return the exact organic clusters allowed across the public handoff.
 *
 * @return string[]
 */
function justice_theme_product_handoff_clusters(): array {
	return array_keys( justice_theme_product_handoff_cluster_owners() );
}

/**
 * Resolve a canonical SEO owner without accepting a public URL.
 */
function justice_theme_product_handoff_owner_path( $cluster ): string {
	$cluster = justice_theme_sanitize_product_handoff_cluster( $cluster );
	$owners  = justice_theme_product_handoff_cluster_owners();

	return $cluster ? $owners[ $cluster ] : '';
}

/**
 * Resolve the canonical product scenario for an allow-listed cluster.
 */
function justice_theme_product_handoff_scenario( $cluster ): string {
	$cluster   = justice_theme_sanitize_product_handoff_cluster( $cluster );
	$scenarios = justice_theme_product_handoff_cluster_scenarios();

	return $cluster ? $scenarios[ $cluster ] : '';
}

/**
 * Accept only the opaque ID format generated by the Justice product.
 */
function justice_theme_sanitize_product_journey_id( $value ): string {
	$value = strtolower( trim( sanitize_text_field( (string) $value ) ) );

	return preg_match( '/^jf-(?:[a-f0-9]{32}|[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12})$/D', $value )
		? $value
		: '';
}

/**
 * Accept a product-origin cluster only from the reconciled GSC vocabulary.
 */
function justice_theme_sanitize_product_handoff_cluster( $value ): string {
	$value = sanitize_key( (string) $value );

	return in_array( $value, justice_theme_product_handoff_clusters(), true ) ? $value : '';
}

/**
 * Accept a scenario only when it is the canonical launch scenario for the
 * selected cluster. Arbitrary query, Matter, or prompt text is rejected.
 */
function justice_theme_sanitize_product_handoff_scenario( $value, $cluster ): string {
	$value    = sanitize_key( (string) $value );
	$expected = justice_theme_product_handoff_scenario( $cluster );

	return '' !== $expected && $value === $expected ? $value : '';
}

/**
 * Read and validate the current product journey.
 */
function justice_theme_current_product_journey_id(): string {
	$value = isset( $_GET['journey_id'] ) ? wp_unslash( $_GET['journey_id'] ) : '';

	return justice_theme_sanitize_product_journey_id( $value );
}

/**
 * Read and validate the current product-origin cluster.
 */
function justice_theme_current_product_handoff_cluster(): string {
	$value = isset( $_GET['cluster'] ) ? wp_unslash( $_GET['cluster'] ) : '';

	return justice_theme_sanitize_product_handoff_cluster( $value );
}

/**
 * Read the current canonical product scenario after cluster validation.
 */
function justice_theme_current_product_handoff_scenario(): string {
	$value = isset( $_GET['scenario'] ) ? wp_unslash( $_GET['scenario'] ) : '';

	return justice_theme_sanitize_product_handoff_scenario(
		$value,
		justice_theme_current_product_handoff_cluster()
	);
}

/**
 * A handoff is trusted only as attribution when source and opaque ID agree.
 * This never authenticates a visitor and never grants access to product data.
 */
function justice_theme_is_current_juris_handoff(): bool {
	$source = isset( $_GET['source'] ) ? sanitize_key( wp_unslash( $_GET['source'] ) ) : '';

	return 'juris-arena' === $source && '' !== justice_theme_current_product_journey_id();
}

/**
 * Return the bounded public query dimensions that may survive navigation.
 *
 * @return array<string,string>
 */
function justice_theme_current_product_handoff_args(): array {
	if ( ! justice_theme_is_current_juris_handoff() ) {
		return array();
	}

	$args = array(
		'source'              => 'juris-arena',
		'journey_id'          => justice_theme_current_product_journey_id(),
		'lead_source_surface' => 'juris_professional_review',
		'utm_source'          => 'jus-tice.com',
		'utm_medium'          => 'product_handoff',
		'utm_campaign'        => 'professional_review',
	);
	$cluster = justice_theme_current_product_handoff_cluster();
	if ( '' !== $cluster ) {
		$args['cluster'] = $cluster;
		$scenario        = justice_theme_current_product_handoff_scenario();
		if ( '' !== $scenario ) {
			$args['scenario'] = $scenario;
		}
	}

	return $args;
}

/**
 * Preserve only the product attribution allow-list on an internal URL.
 */
function justice_theme_append_current_product_handoff_args( string $url ): string {
	$args = justice_theme_current_product_handoff_args();

	return empty( $args ) ? $url : add_query_arg( $args, $url );
}

/**
 * Resolve the strict cumulative CRM stages for product funnel reporting.
 *
 * @return array{qualified:bool,accepted:bool,closed:bool,won:bool}
 */
function justice_theme_product_handoff_stage_flags( string $status, string $follow_up ): array {
	$status    = sanitize_key( $status );
	$follow_up = sanitize_key( $follow_up );

	return array(
		'qualified' => in_array( $status, array( 'qualified', 'accepted', 'converted' ), true ) || in_array( $follow_up, array( 'consult_scheduled', 'won' ), true ),
		'accepted'  => in_array( $status, array( 'accepted', 'converted' ), true ) || in_array( $follow_up, array( 'consult_scheduled', 'won' ), true ),
		'closed'    => in_array( $status, array( 'rejected', 'converted', 'closed' ), true ) || in_array( $follow_up, array( 'not_qualified', 'won', 'lost' ), true ),
		'won'       => 'converted' === $status || 'won' === $follow_up,
	);
}
