-- Reviews table schema definition for Supabase PostgreSQL
-- Supports both UUID and auto-incrementing integer for the primary key.
-- Includes Row-Level Security (RLS) policies for secure public submission and admin management.

-- Option A: Using UUID for ID (Recommended for distributed systems and Supabase best practices)
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reviewer_name TEXT NOT NULL CONSTRAINT name_not_empty CHECK (char_length(trim(reviewer_name)) > 0),
    reviewer_role TEXT NOT NULL CONSTRAINT valid_role CHECK (reviewer_role IN ('Client', 'Colleague', 'Google')),
    rating INTEGER NOT NULL CONSTRAINT valid_rating CHECK (rating >= 1 AND rating <= 5),
    content TEXT NOT NULL CONSTRAINT content_not_empty CHECK (char_length(trim(content)) > 0),
    approval_status BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Option B: Using Auto-incrementing Bigint for ID
-- If this option is preferred, comment out the table above and uncomment below:
/*
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_name TEXT NOT NULL CONSTRAINT name_not_empty CHECK (char_length(trim(reviewer_name)) > 0),
    reviewer_role TEXT NOT NULL CONSTRAINT valid_role CHECK (reviewer_role IN ('Client', 'Colleague', 'Google')),
    rating INTEGER NOT NULL CONSTRAINT valid_rating CHECK (rating >= 1 AND rating <= 5),
    content TEXT NOT NULL CONSTRAINT content_not_empty CHECK (char_length(trim(content)) > 0),
    approval_status BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
*/

-- Indexing for performance
CREATE INDEX IF NOT EXISTS idx_reviews_approval_status ON public.reviews (approval_status);
CREATE INDEX IF NOT EXISTS idx_reviews_role ON public.reviews (reviewer_role) WHERE approval_status = true;

-- Enable Row Level Security (RLS)
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- POLICIES:
-- 1. Allow public read of approved reviews (Anonymous/Guest users can see approved reviews)
CREATE POLICY "Allow public read of approved reviews" 
ON public.reviews 
FOR SELECT 
USING (approval_status = true);

-- 2. Allow public insertion of reviews (Anonymous/Guest users can submit new reviews, but they default to pending approval)
CREATE POLICY "Allow public submission of pending reviews" 
ON public.reviews 
FOR INSERT 
WITH CHECK (approval_status = false);

-- 3. Allow authenticated admins to select all reviews (including pending)
CREATE POLICY "Allow admins to read all reviews"
ON public.reviews
FOR SELECT
TO authenticated
USING (true);

-- 4. Allow authenticated admins to update reviews (e.g. approve them or edit)
CREATE POLICY "Allow admins to update reviews"
ON public.reviews
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

-- 5. Allow authenticated admins to delete reviews
CREATE POLICY "Allow admins to delete reviews"
ON public.reviews
FOR DELETE
TO authenticated
USING (true);
